name: Frutter CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install frappe

    - name: Install Frappe Bench
      run: |
        git clone https://github.com/frappe/bench.git
        pip install -e bench

    - name: Run unit tests
      run: |
        pytest tests/
        find frutter_cicd/frutter_cicd/doctype/ -name 'test_*.py' -exec pytest {} \;

    - name: Check for test cases
      run: |
        # file_name=$(basename $GITHUB_WORKSPACE/$GITHUB_EVENT_NAME)
        file_name=$(basename $GITHUB_WORKSPACE/$GITHUB_SHA)
        test_file="${file_name//.py/_test.py}"
        if [[ -f "tests/$test_file" || -f "frutter_cicd/frutter_cicd/doctype/$test_file" ]]; then
          echo "Test file $test_file found."
          pytest "tests/$test_file" "frutter_cicd/frutter_cicd/doctype/$test_file"
        else
          echo "Test file $test_file not found."
          exit 1
        fi

    - name: Merge develop into current branch
      run: git merge develop --no-commit --no-ff || echo "Conflict occurred"

    - name: Check for merge conflicts
      run: git diff --quiet && echo "No conflicts" || (echo "Conflicts found"; exit 1)
